import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { AOSProvider } from "@/components/AOSProvider";
import { LanguageProvider } from "@/context/LanguageContext";
import { LoadingProvider } from "@/context/LoadingContext";
import LoaderOverlay from "@/components/LoaderOverlay";
import { RouteChangeListener } from "@/components/RouteChangeListener";
import { Suspense } from 'react'; // Import Suspense
// import ScrollToTopButton from "@/components/ui/ScrollToTopButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: 'Petroseal',
    template: '%s - Petroseal',
  },
  description: "Generated by Tricode.id",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <LoadingProvider>
          <LoaderOverlay />
          <Suspense fallback={null}> {/* Wrap RouteChangeListener with Suspense */}
            <RouteChangeListener />
          </Suspense>
          <AOSProvider>
            <LanguageProvider>{children}</LanguageProvider>
          </AOSProvider>
          {/* <ScrollToTopButton /> */}
        </LoadingProvider>
      </body>
    </html>
  );
}