import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { AOSProvider } from "@/components/AOSProvider";
import { LanguageProvider } from "@/context/LanguageContext";
import { LoadingProvider } from "@/context/LoadingContext";
import LoaderOverlay from "@/components/LoaderOverlay";
import { RouteChangeListener } from "@/components/RouteChangeListener";
import { Suspense } from 'react'; // Import Suspense
// import ScrollToTopButton from "@/components/ui/ScrollToTopButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: 'Petroseal Engineering Sdn Bhd',
    template: '%s - Petroseal Engineering Sdn Bhd',
  },
  description: "Generated by Tricode.id",
  icons: {
    icon: [
      { url: '/images/favicon/favicon.ico', sizes: 'any' },
      { url: '/images/favicon/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/images/favicon/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: [
      { url: '/images/favicon/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
    other: [
      { url: '/images/favicon/android-chrome-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/images/favicon/android-chrome-512x512.png', sizes: '512x512', type: 'image/png' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <LoadingProvider>
          <LoaderOverlay />
          <Suspense fallback={null}> {/* Wrap RouteChangeListener with Suspense */}
            <RouteChangeListener />
          </Suspense>
          <AOSProvider>
            <LanguageProvider>{children}</LanguageProvider>
          </AOSProvider>
          {/* <ScrollToTopButton /> */}
        </LoadingProvider>
      </body>
    </html>
  );
}